baseURL: https://asc-website-jacob-stachowicz.netlify.app/
languageCode: en-us
title: title
copyright: Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved.
theme: npqhugo
pygmentsUseClasses: yeshugo
params:
  author: your name
  description: your description
  displayMicroBlog: no
  displayRecent: yes
  formspreeID: yourformspreeID
  keywords: hugo blog
  mail: mail@example.com
  microBlogSection: posts
  phone: '8888888888'
  recentMax: 3
  useAvatar: yes
menu:
  main:
    - name: home
      pre: <i class="fas fa-home fa-sm"></i>
      url: /
      weight: -9
    - name: blog
      pre: <i class="fas fa-keyboard fa-ms"></i>
      url: /blog/
      weight: -8
    - name: tags
      pre: <i class="fas fa-tags fa-ms"></i>
      url: /tags
      weight: -7
    - name: github
      pre: <i class="fab fa-github fa-ms"></i>
      url: https://github.com/yourgithubusername23434
      weight: -6
    - name: RSS
      pre: <i class="fas fa-rss fa-ms"></i>
      url: /index.xml
      weight: -4
    - name: contact
      pre: <i class="far fa-envelope"></i>
      url: /contact
      weight: -1

markup:
  goldmark:
    renderer:
      unsafe: true
